name: simple_ads_manager
description: An easy-to-use Flutter plugin for integrating all Google Mobile Ads formats, including banner, native, interstitial, and rewarded ads, to maximize app revenue.
version: 1.1.1
license: MIT
homepage: https://engzeeshanali.github.io/

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^7.0.0


plugin:
  platforms:
    android:
    ios:

